version: '3'

services:
  web:
    image: arsenydeveloper/django-movie-dev:latest
    restart: always
    command: sh -c "make migrate && make rungunicorn"
    ports:
      - 8000:8000
    volumes:
      - static-volume:/app/django-movie/static
      - media-volume:/app/django-movie/media
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    volumes:
      - dmp-postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  dmp-postgres-data:
  static-volume:
  media-volume:

