version: '3'

services:
  web:
    build:
      context: .
    command: sh -c "make migrate && make rungunicorn"
    ports:
      - 8000:8000
    volumes:
      - static_volume:/app/django_movie/static
      - media_volume:/app/django_movie/media
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    volumes:
      - dmp_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  dmp_postgres_data:
  static_volume:
  media_volume:
