# Generated by Django 4.1 on 2022-09-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_review_movie_alter_review_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='star',
            new_name='star_id',
        ),
    ]
