# Generated by Django 4.1 on 2022-12-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_movie_id_rating_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Not stated', max_length=150, verbose_name='category'),
        ),
    ]
