# Generated by Django 4.1 on 2022-12-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(default='Not stated', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.category', verbose_name='Category'),
        ),
    ]
