# Generated by Django 4.1 on 2022-12-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default=None, max_length=5000, verbose_name='message'),
            preserve_default=False,
        ),
    ]
