# Generated by Django 4.1 on 2023-01-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_actor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='user',
        ),
    ]
