# Generated by Django 4.1 on 2023-01-09 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_actor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='first_creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
