# Generated by Django 4.1 on 2023-01-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_actor_first_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_creation_date',
            new_name='first_creation_time',
        ),
        migrations.AddField(
            model_name='actor',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
