# Generated by Django 4.1 on 2023-04-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
