# Generated by Django 4.1 on 2023-04-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_remove_review_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Category'),
        ),
    ]
