# Generated by Django 4.1 on 2023-04-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='movies.actor', verbose_name='Actors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movie_genre', to='movies.genre', verbose_name='Genres'),
        ),
    ]
