# Generated by Django 4.1 on 2023-04-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0029_alter_movie_actors_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movie_actor', to='movies.actor', verbose_name='Actors'),
        ),
    ]
