# Generated by Django 4.1 on 2023-04-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
