# Generated by Django 4.1 on 2023-04-27 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_rename_star_rating_acting_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='star',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
