# Generated by Django 4.1 on 2023-04-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0036_rating_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='star',
        ),
    ]
