# Generated by Django 4.1 on 2023-04-27 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0037_remove_rating_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='total_rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
